<?php
namespace app\controller;

use app\models\Countries;
use app\BaseController;
use think\Exception;
use think\facade\Db;

class Api extends BaseController
{
    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
    }


    /**
     * get country data
     * @return \think\response\Json
     * @throws \think\db\exception\DataNotFoundException
     * @throws \think\db\exception\ModelNotFoundException
     * @throws \think\exception\DbException
     */
    public function getCountries()
    {
        $list = Db::name(Countries::$tablename)->where("state", 1)->order("sortorder ASC")->select();
        $countries = [];
        if(!empty($list)) {
            foreach($list as $v) {
                $pid = "_".$v["pid"];
                $id = "_".$v['id'];
                $countries[$pid][$id] = $v["name"];
            }
        }

        return json($countries);
    }
    
    public function getCountriesByPid()
    {
        $pid = input("pid", 0);
        if(!empty($pid)) {
            $list = Db::name(Countries::$tablename)->where("state", 1)->where("pid", $pid)->order("sortorder ASC")->select();
            $countries = [];
            if(!empty($list)) {
                foreach($list as $v) {
                    $countries["_".$v['id']] = $v["name"];
                }
            }
            return json($countries);
        } else {
            return json([]);
        }
    }

    public function getPostcodeByCountryId()
    {
        try {
            $id = input("id", 0);
            if (empty($id)) {
                throw new Exception("無效ID");
            }
            $postcode = Db::name("countries")->where("id", $id)->value("postcode");
            if(empty($postcode)) {
                throw new Exception("未找到郵政區號");
            }
            return $postcode;
        } catch (Exception $ex) {
            return;
        }
    }

}
